package io.github.son1004007.opsmate.domain;

public enum ErrorCode {
    UNAUTHORIZED_ACTION,
    NOT_FOUND,
    INVALID_STATE,
    IDEMPOTENCY_CONFLICT,
    MODEL_UNAVAILABLE,
    INVALID_MODEL_OUTPUT,
    POLICY_NOT_FOUND,
    DUPLICATE_ORDER,
    WRITE_CONFLICT,
    VALIDATION_ERROR,
    ORDER_FINALIZATION_FAILED,
    SESSION_EXPIRED,
    DEMO_CLOSED,
    DEMO_CAPACITY_REACHED,
    RATE_LIMITED,
    MODEL_BUSY
}
